stages: [commit]
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
        -   id: check-added-large-files
        -   id: check-docstring-first
        -   id: detect-private-key
        -   id: debug-statements
        -   id: double-quote-string-fixer
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

    -   repo: https://github.com/jorisroovers/gitlint
        rev: v0.17.0
        hooks:
        -   id: gitlint

    -   repo: https://github.com/PyCQA/flake8
        rev: 4.0.1
        hooks:
        -   id: flake8
            additional_dependencies: [flake8-typing-imports==1.7.0]


    -   repo: https://github.com/psf/black
        rev: 19.3b0
        hooks:
        -   id: black

    -   repo: local
        hooks:
            - id: mypy
              name: mypy
              entry: pipenv run check-types
              language: system
              types: [python]
              pass_filenames: false
